name: build

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: install dependencies
        run: |
          choco install cuda --no-progress -y
          choco upgrade all -y
      - name: Checkout
        uses: actions/checkout@v3          
      - name: run media-autobuild
        shell: cmd
        run: |
          cd media-autobuild_suite
          ./media-autobuild_suite.bat
