name: build

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run media-autobuild
        shell: cmd
        run: |
          choco install cuda
          cd media-autobuild_suite
          ./media-autobuild_suite.bat
          
